### PR TITLE
Integrate pre activity metadata and receive tags

### LINKED ISSUE #197: Cannot add tag on editing receive invoice
Test: `@onchain_2`
**Steps to reproduce:**
1. Have a new wallet
2. Hit Receive > Edit
3. Try to add tag

**Expected:**
After adding a tag it should be visible on the Edit sheet.

**Actial:**
Tag is not visible after adding.

https://github.com/user-attachments/assets/a1493a1b-6ddf-4988-9d2c-5c15ea1ea6ee

### PR DESCRIPTION
**Pull request by ben-kaufman**
This PR integrates pre-activity metadata from Bitkit Core.

Fixes #197 

The pre-activity metadata is created before the send/ receive activities are created, and allow Bitkit Core to automatically add tags to an activity once created (for sent txs, the previous logic to apply tags was removed). Also for sent txs, it let's Bitkit Core auto fill the address for the activity, and for receive txs it helps in a more efficient lookup for the address the activity belongs to.

This PR also extracts certain UI components related to tags and reuses them across the app.
It also fixes the VSS backup to correctly backup and restore activities tags and pre-activity metadata.

https://github.com/user-attachments/assets/7a962759-251d-466e-b220-2064365821c8

### CODE REVIEW

File: Bitkit/Services/CoreService.swift [hunk 1]
```diff
@@ -235,6 +246,118 @@ class ActivityService {
...
+        // Try receiving addresses first, then change addresses
+        if let address = try await searchAddresses(isChange: false) {
+            return address
+        }
+        if let address = try await searchAddresses(isChange: true) {
+            return address
+        }
+
+        // Fallback: return first output address
+        return txDetails.vout.first?.scriptpubkey_address ?? "todo_find_address"
```
[the remark this answers is not in the document]
Comment (ben-kaufman) [reply Bitkit/Services/CoreService.swift]: It is what we had before. In theory it should never happen, do you have any suggestions for a better fallback?

**Comment by jvsena42** [comment]
Roadmap item
https://docs.google.com/spreadsheets/d/1NBtx1y-_ZcODo8L0LsbudBNV_9x7cF6MyckR_W1xxq4/edit?pli=1&gid=0#gid=0&range=C14

File: Bitkit/Views/Wallets/Receive/ReceiveSheet.swift [hunk 2]
```diff
@@ -45,8 +46,11 @@ struct ReceiveSheet: View {
         .onAppear {
             wallet.invoiceAmountSats = 0
             wallet.invoiceNote = ""
+            tagManager.clearSelectedTags()
             Task {
                 try? await wallet.refreshBip21(forceRefreshBolt11: true)
+                // Create pre-activity metadata after refreshing the invoice/address
+                await wallet.persistPreActivityMetadata()
```
Comment (jvsena42) [inline Bitkit/Views/Wallets/Receive/ReceiveSheet.swift]: could delete data with more than 48 hours or with expired invoices, because this method is called multiple times

Comment (ben-kaufman) [reply Bitkit/Views/Wallets/Receive/ReceiveSheet.swift]: I don't think we should really. If a payment is received then the pre activity is deleted automatically in bitkit core, and if it's not received then it will either be replaced once the user reopens the receive tab, or the user might still be waiting for a payment. So either way I don't see why we should delete after 48 hours.

**Comment by ben-kaufman** [comment]
Issue should now be fixed @jvsena42 

Testing instructions are as you did + click in savings balance -> transfer to spending -> make sure the resulting activity is shown as transfer.

File: Bitkit/Models/BackupPayloads.swift [hunk 3]
```diff
@@ -12,7 +12,7 @@ struct WalletBackupV1: Codable {
 struct MetadataBackupV1: Codable {
     let version: Int
     let createdAt: UInt64
-    let tagMetadata: [ActivityTagsMetadata]
+    let tagMetadata: [PreActivityMetadata]
```
Comment (ovitrif) [inline Bitkit/Models/BackupPayloads.swift]: should we name it `preActivityMetadata`? I can do the same in Android ;)

Or even `activityMetadata`, since we won't likely have a different activity metadata soon 🤷🏻

**Comment by ovitrif** [comment]
> Issue should now be fixed @jvsena42
> 
> Testing instructions are as you did + click in savings balance -> transfer to spending -> make sure the resulting activity is shown as transfer.

You mean on the previous PR that was closed in favour of this?!

**Review by jvsena42 — APPROVED** [review]
**Lightning**

- Create invoice -> add tags and description -> receive -> check if tags and description were added ✅
- scan invoice -> add tags -> send -> check tags ✅

**On-chain**

- Create BIP 21 invoice -> add tags -> receive -> activity details -> check tags ✅
- Scan BIP 21 invoice -> add tags -> send -> activity details -> check address, fee, federate and tags ✅
- Transfer to spending ✅
- Reset and restore ✅

OBS: On transfer to spending, the pending transfer activities are not being displayed. They are only displayed after confirmed. (can be fixed in #226 )


https://github.com/user-attachments/assets/4d56153a-ebf1-4c85-80f3-d0bfccd9c4a6

**Review by ovitrif — COMMENTED** [review]
### Tests
1. Receive Tags: all tests ok 🟢 
2. Transfer: test ok 🟢 
3. Send Tags: all tests ok 🟢 

---

While testing receive tags, In found an issue not added in these changes, but related to the feature.

Receive > Edit > Tap Note textfield > **Can't add tags anymore**
Really need to show QR code and then edit again.
